//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.19 at 04:43:19 PM CEST 
//


package com.semmtech.laces.fetch.imports.relatics.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.semmtech.laces.fetch.imports.relatics package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.semmtech.laces.fetch.imports.relatics
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetResult }
     * 
     */
    public GetResult createGetResult() {
        return new GetResult();
    }

    /**
     * Create an instance of {@link Import }
     * 
     */
    public Import createImport() {
        return new Import();
    }

    /**
     * Create an instance of {@link ImportResponse }
     * 
     */
    public ImportResponse createImportResponse() {
        return new ImportResponse();
    }

    /**
     * Create an instance of {@link ImportResponse.ImportResult }
     * 
     */
    public ImportResponse.ImportResult createImportResponseImportResult() {
        return new ImportResponse.ImportResult();
    }

    /**
     * Create an instance of {@link ImportResponse.ImportResult.Import }
     * 
     */
    public ImportResponse.ImportResult.Import createImportResponseImportResultImport() {
        return new ImportResponse.ImportResult.Import();
    }

    /**
     * Create an instance of {@link ImportResponse.ImportResult.Import.Elements }
     * 
     */
    public ImportResponse.ImportResult.Import.Elements createImportResponseImportResultImportElements() {
        return new ImportResponse.ImportResult.Import.Elements();
    }

    /**
     * Create an instance of {@link Authentication }
     * 
     */
    public Authentication createAuthentication() {
        return new Authentication();
    }

    /**
     * Create an instance of {@link Identification }
     * 
     */
    public Identification createIdentification() {
        return new Identification();
    }

    /**
     * Create an instance of {@link GetResult.Parameters }
     * 
     */
    public GetResult.Parameters createGetResultParameters() {
        return new GetResult.Parameters();
    }

    /**
     * Create an instance of {@link ImportResponse.ImportResult.Import.Message }
     * 
     */
    public ImportResponse.ImportResult.Import.Message createImportResponseImportResultImportMessage() {
        return new ImportResponse.ImportResult.Import.Message();
    }

    /**
     * Create an instance of {@link ImportResponse.ImportResult.Import.Elements.Element }
     * 
     */
    public ImportResponse.ImportResult.Import.Elements.Element createImportResponseImportResultImportElementsElement() {
        return new ImportResponse.ImportResult.Import.Elements.Element();
    }

    /**
     * Create an instance of {@link InnerAuthentication }
     * 
     */
    public InnerAuthentication createInnerAuthentication() {
        return new InnerAuthentication();
    }

    /**
     * Create an instance of {@link InnerIdentification }
     * 
     */
    public InnerIdentification createInnerIdentification() {
        return new InnerIdentification();
    }

}
